// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('ops', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('ops', async function() {
    // Test name: ops
    // Step # | name | target | value
    // 1 | open | /dashboard | 
    await driver.get("http://localhost:3001/dashboard")
    // 2 | setWindowSize | 1407x815 | 
    await driver.manage().window().setRect({ width: 1407, height: 815 })
    // 3 | click | xpath=//div[@id='product']/div/div/div[2] | 
    await driver.findElement(By.xpath("//div[@id=\'product\']")).click()
    // 4 | click | xpath=//div[@id='react-select-2-option-1'] | 
    await driver.findElement(By.xpath("//div[@id=\'react-select-2-option-1\']")).click()
    // 5 | click | xpath=//div[@id='accountType']/div/div/div[2] | 
    await driver.findElement(By.xpath("//div[@id=\'accountType\']")).click()
    // 6 | click | xpath=//div[@id='eFD'] | 
    await driver.findElement(By.xpath("//div[@id=\'eFD\']")).click()
    // 7 | click | xpath=//div[@id='fdAccountNo']/div/div/div[2] | 
    await driver.findElement(By.xpath("//div[@id=\'fdAccountNo\']")).click()
    // 8 | click | xpath=//div[@id='433423332212'] | 
    await driver.findElement(By.xpath("//div[@id=\'433423332212\']")).click()
    // 9 | click | xpath=//div[@id='fromBank']/div/div/div[2] | 
    await driver.findElement(By.xpath("//div[@id=\'fromBank\']")).click()
    // 10 | click | xpath=//div[@id='CIMB'] | 
    await driver.findElement(By.xpath("//div[@id=\'CIMB\']")).click()
    // 11 | click | xpath=//div[@id='fdAccountNo']/div/div/div[2] | 
    await driver.findElement(By.xpath("//div[@id=\'fdAccountNo\']")).click()
    // 12 | click | xpath=//div[@id='433411182212'] | 
    await driver.findElement(By.xpath("//div[@id=\'433411182212\']")).click()
    // 13 | click | id=next | 
    await driver.manage().setTimeouts( { implicit: 1000000 } );

    await driver.findElement(By.id("next")).click()
  })
})
