// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
      
describe('ops', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('ops', async function() {
    // Test name: ops
    // Step # | name | target | value
    // 1 | open | /dashboard | 
    await driver.get("http://localhost:3001/dashboard")
    // 2 | setWindowSize | 1407x815 | 
    await driver.manage().window().setRect({ width: 1407, height: 815 })
         
    // 3 | click | xpath=//div[@id='BOO5f8xtfL'] | 
    await driver.findElement(By.xpath("//div[@id='BOO5f8xtfL']")).getText()     
    // 4 | click | xpath=//div[@id='JOcX2JB7it'] | 
    await driver.findElement(By.xpath("//div[@id='JOcX2JB7it']")).getText()     
    // 5 | click | xpath=//div[@id='i#jD#P2aeQ'] | 
    await driver.findElement(By.xpath("//div[@id='i#jD#P2aeQ']")).getText()     
    // 6 | click | xpath=//div[@id='account'] | 
    await driver.findElement(By.xpath("//div[@id='account']")).getText()     
    // 7 | click | xpath=//div[@id='I2HCE5BURU'] | 
    await driver.findElement(By.xpath("//div[@id='I2HCE5BURU']")).getText()     
    // 8 | click | xpath=//div[@id='XXhpxWX9kI'] | 
    await driver.findElement(By.xpath("//div[@id='XXhpxWX9kI']")).getText()     
    // 9 | click | xpath=//div[@id='recipientbank'] | 
    await driver.findElement(By.xpath("//div[@id='recipientbank']")).getText()     
    // 10 | click | xpath=//div[@id='accountNumber'] | 
    await driver.findElement(By.xpath("//div[@id='accountNumber']")).getText()     
    // 11 | click | xpath=//div[@id='mMOR0x8Hwg'] | 
    await driver.findElement(By.xpath("//div[@id='mMOR0x8Hwg']")).getText()     
    // 12 | click | xpath=//div[@id='recipientName'] | 
    await driver.findElement(By.xpath("//div[@id='recipientName']")).getText()     
    // 13 | click | xpath=//div[@id='amount'] | 
    await driver.findElement(By.xpath("//div[@id='amount']")).getText()     
    // 14 | click | xpath=//div[@id='ooYDh7Tjr#'] | 
    await driver.findElement(By.xpath("//div[@id='ooYDh7Tjr#']")).click()
  })
})
